export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const FEED_LOADING = 'FEED_LOADING';
export const FEED_FAILED = 'FEED_FAILED';
export const FEED_LOADED = 'FEED_LOADED';
export const ADD_IMAGE = 'ADD_IMAGE';

export const POST_GIF_SUCCESS = 'POST_GIF_SUCCESS';
export const POST_GIF_LOADING = 'POST_GIF_LOADING';
export const POST_GIF_FAILED = 'POST_GIF_FAILED';

export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_COMMENT_FAILED = 'ADD_COMMENT_FAILED';
export const ADD_ITEM_AND_COMMENTS = 'ADD_ITEM_AND_COMMENTS';
export const ITEM_AND_COMMENTS_LOADING = 'ITEM_AND_COMMENTS_LOADING';
export const ITEM_AND_COMMENTS_FAILED = 'ITEM_AND_COMMENTS_FAILED';

export const ADD_ARTICLE = 'ADD_ARTICLE';
export const ADD_ARTICLE_FAILED = 'ADD_ARTICLE_FAILED';

export const ADD_ARTICLE_AND_COMMENTS = 'ADD_ARTICLE_AND_COMMENTS';
export const ARTICLE_AND_COMMENTS_LOADING = 'ARTICLE_AND_COMMENTS_LOADING';
export const ARTICLE_AND_COMMENTS_FAILED = 'ARTICLE_AND_COMMENTS_FAILED';

export const ADD_ARTICLE_COMMENT_FAILED = 'ADD_ARTICLE_COMMENT_FAILED';
export const ADD_ARTICLE_COMMENT = 'ADD_ARTICLE_COMMENT';

export const DELETE_IMAGE = 'DELETE_IMAGE';
export const DELETE_IMAGE_FAILED = 'DELETE_IMAGE_FAILED';

export const UPDATE_ARTICLE = 'UPDATE_ARTICLE';
export const UPDATE_ARTICLE_FAILED = 'UPDATE_ARTICLE_FAILED';

export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const DELETE_ARTICLE_FAILED = 'DELETE_ARTICLE_FAILED';

export const UPDATE_POSTED_ARTICLE = 'UPDATE_POSTED_ARTICLE';
export const UPDATE_POSTED_ARTICLE_FAILED = 'UPDATE_POSTED_ARTICLE_FAILED';

export const DELETE_POSTED_ARTICLE = 'DELETE_POSTED_ARTICLE';
export const DELETE_POSTED_ARTICLE_FAILED = 'DELETE_POSTED_ARTICLE_FAILED';

export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_LOADING = 'CREATE_USER_LOADING';
export const CREATE_USER_FAILED = 'CREATE_USER_FAILED';




